camera: camera.cpp
	g++ camera.cpp -o camera `pkg-config --cflags --libs opencv`

evidence_finger_tracking: finger_tracker.cpp evidence_finger_tracker.cpp
	g++ evidence_finger_tracker.cpp finger_tracker.cpp -o evidence_finger_tracker `pkg-config --cflags --libs opencv`

	
