camera: camera.cpp
	g++ camera.cpp -o camera `pkg-config --cflags --libs opencv`

finger_tracking: finger_tracking.cpp
	g++ finger_tracking.cpp -o finger_tracker `pkg-config --cflags --libs opencv`

	
